# Codecov configuration for mcp-gitlab
# https://docs.codecov.io/docs/codecov-yaml

codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        paths:
          - "src/"
        if_not_found: success
        informational: false
        only_pulls: false
    
    patch:
      default:
        target: 80%
        threshold: 1%
        base: auto
        if_not_found: success
        informational: false
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

ignore:
  - "tests/**/*"
  - "**/__pycache__/**/*"
  - "setup.py"
  - "**/test_*.py"
  - "**/*_test.py"
  - "docs/**/*"
  - "examples/**/*"
  - ".github/**/*"

flags:
  unittests:
    paths:
      - src/
    carryforward: false
    target: 80%